### PR TITLE
Features/assetfees

### PR DESCRIPTION
**Pull request by steveeakin**
Handling trades where you are paying the fees in the traded asset, resulting in a net deduction in tradable assets for the next leg of the triangle. Fixes issue #54

### CODE REVIEW

**Comment by bmino** [comment]
Looks like this is still a work in progress?

Why would somebody run this bot if they were not using BNB to pay fees? I think a more likely scenario is that the bot is run for a long period of time and the BNB balance is depleted or used in another transaction. In these cases it would be helpful to not execute a position.

ie. don't execute a position if fees will be paid in terms of the assets involved, otherwise fail with an insufficient balance

**Comment by steveeakin** [comment]
This is what I ran into - Run it for a long, long time and run out of BNB.  I still want to execute a trade that fits my criteria, as they're still profitable regardless of how the fees are paid.

**Comment by steveeakin** [comment]
Perhaps we can put a new config var in place that would execute withe the base asset as the fee if you run out of BNB?

**Comment by bmino** [comment]
It should probably not execute if BNB cannot be used to pay the fee as that would incur a cost not expected in the original calculation likely turning any trade into a net loss

**Pull request closed without merging**
